name: kc-minecraft-provider
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10

  keycloak:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Admin-User für Keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DEBUG: "true"
      DEBUG_PORT: '8787'

      # DB-Anbindung
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    command: ["start-dev"]
    ports:
      - "8999:8080"
      - "8787:8787"

volumes:
  db_data:
